use_frameworks!
platform :ios, '10.0'

target 'SomeCoolStuff_Example' do
  pod 'SomeCoolStuff', :path => '../'

  target 'SomeCoolStuff_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.1.0'
    pod 'Nimble', '7.0.1'
  end
end
