use_frameworks!

target 'SomeCoolStuff_Example' do
  pod 'SomeCoolStuff', :path => '../'

  target 'SomeCoolStuff_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
